### ISSUE TITLE
shortcuts no response

### ISSUE THREAD

**Issue by growingtreesss** [c3founder/Roam-Enhancement#1]
## Backround
- Shortcuts didn't work in my computer(Mac/Win), replace 'alt' with 'ctrl','command','option',no responds neither
- System(Mac:Version 10.15.4, Win:64-bit Operating System i3)
## Steps:
- install roam42
- install codes in https://c3founder.github.io/Roam-Enhancement/
- embed youtube video in roam
- use shortcuts in a child block of the YT video

(code block is indented under {{[[roam/js]]}})
## Previous Tries
- changed 'alt' with another shortcut(did't work)
- switched to Win(didn't work)

## Guess
- Are there any steps missing?

**Comment by growingtreesss** [comment]
original discussion is in [here](https://gist.github.com/c3founder/0d47fe3f15f677a0a6f0e96b4868e46a#gistcomment-3588393)

**Comment by DarkArcZ** [comment]
I had the same problem as you as mac user where I was not able to use the keyboard shortcuts. After changing my keyboard Input Sources to "Unicode Hex Input" from the original "ABC", and then changing the keyboard shortcuts to something else besides alt (I used ctrl), I was able to use the shortcuts.

Instructions:
1. Go to Keyboard on your Mac System Preferences
2. Click on Input Sources on the top
3. Press the "+" button and add "Unicode Hex Input"
4. Go to where you pasted the code on roam
5. Change the shortcut key to something else besides alt (cmd, option, ctrl)
6. Restart Roam

That did the trick for me

**Comment by growingtreesss** [comment]
> I had the same problem as you as mac user where I was not able to use the keyboard shortcuts. After changing my keyboard Input Sources to "Unicode Hex Input" from the original "ABC", and then changing the keyboard shortcuts to something else besides alt (I used ctrl), I was able to use the shortcuts.
> 
> Instructions:
> 
> 1. Go to Keyboard on your Mac System Preferences
> 2. Click on Input Sources on the top
> 3. Press the "+" button and add "Unicode Hex Input"
> 4. Go to where you pasted the code on roam
> 5. Change the shortcut key to something else besides alt (cmd, option, ctrl)
> 6. Restart Roam
> 
> That did the trick for me

thanks, I've changed the shortcut to ctrl before, it did't work. use a win to test, didn't work either. I guess there might be something wrong with my code installation,  just don't have clue, however.

**Comment by c3founder** [comment]
@growingtreesss do you still have this issue? 

common installation problem: you need to have the code block as the child of {{[[roam/js]]}} so you need a tab: 
{{[[roam/js]]}}
    ```javascript
    ```
    
another common issue: 
say you use alt+a n for the timestamp. sometimes alt+a is already is assigned to some other action in your OS/browser. Try changing that. 

Don't forget that you need to release after alt+a (like alt+tab in Windows to switch between windows) and then press n.

**Comment by LeximusMG** [comment]
I'm using a mac. I've changed the shortcuts to ctrl+a n and ctrl+a t but for some reason it's not picking up the change. The new shortcut is does nothing but the original alt+ still works (even though I'm on a mac). Any ideas?

**Comment by c3founder** [comment]
I think that is because your browser (or one of the installed apps/extensions) picks it up first. Usually hard to figure out which one. Do ablation.

**Comment by growingtreesss** [comment]
@c3founder Thanks for your patience, 'ctrl' works well. 
> Don't forget that you need to release after alt+a (like alt+tab in Windows to switch between windows) and then press n.

that's the key😄

hold the 'ctrl' ,then click 'a'('ctrl' is still holding),then release both, quick click 'n', time will show up as expected

**Comment by growingtreesss** [comment]
> I'm using a mac. I've changed the shortcuts to ctrl+a n and ctrl+a t but for some reason it's not picking up the change. The new shortcut is does nothing but the original alt+ still works (even though I'm on a mac). Any ideas?

@LeximusMG I also encountered this problem before, because I held down ‘ctrl’ and ‘a’ at the same time at the beginning, maybe you can also recheck how you press them, try a few more times, hope it helps
