### ISSUE TITLE
List of parameters 

### ISSUE THREAD

**Issue by cocoaaa** [c3founder/Roam-Enhancement#20]
Hi, thank you for sharing these useful extensions!

I'm watching the tutorial video on Enhancement PDF and saw there are customizable parameters: e.g.
![image](https://user-images.githubusercontent.com/8037983/113369696-c5154080-9316-11eb-80ef-8897577e1392.png)

Is there a documentation of all available parameters (name, values)?

Thanks!

**Comment by c3founder** [comment]
Hi, they are all explained in the full demo. Follow the timestamps: 
https://www.youtube.com/watch?v=-yVqQqUEHKI
