### ISSUE TITLE
The link from the extracted highlight to the position in the PDF stopped working 

### ISSUE THREAD

**Issue by ll7** [c3founder/Roam-Enhancement#22]
The link from the extracted highlight to the position in the PDF stopped working for me. The link had a round shape previously. Now it is rectangular and doesn't move the focus to the highlight in the PDF.

![FNqKq1RZQC](https://user-images.githubusercontent.com/32880741/116250778-52a94c00-a76e-11eb-9818-554a3f618a0b.png)

This seems to appear more often in the right sidebar. It sometimes helps to reload the corresponding PDF by entering the edit mode of the PDF block.

**Comment by cameroncruz** [comment]
I'm also encountering this bug. Can confirm reloading the PDF by entering edit mode as @ll7 describes fixes links for existing highlights. However, subsequent highlights are generated with broken links and require another reload to be fixed.

**Comment by dpwanjala** [comment]
I can confirm that I am unable to get the link to work from time to time. It seems to me the links stop working arbitrarily. At some point they function and then at another point they don't. This could be after a page reload or editing the highlight block or opening the highlights on the sidebar. It is therefore difficult for me to figure out why they keep working correctly at random times.

**Comment by liu51115** [comment]
I'm also having the same issue. It works on the MacOS app, but doesn't work in the web version.

**Comment by c3founder** [comment]
Can anyone confirm that this is resolved after the latest update? Thanks!

**Comment by ll7** [comment]
I can confirm that this bug no longer appears to happen.
Thank you.
