### ISSUE TITLE
PDF viewer issue in roam

### ISSUE THREAD

**Issue by IsablleD** [c3founder/Roam-Enhancement#27]
Anyone experiences the same thing when after uploading PDF into roam? It was opened in roam using adobe viewer for some reason. The plugin does not work in such case.

<img width="608" alt="WechatIMG134" src="https://user-images.githubusercontent.com/34254564/121478914-81cef200-c997-11eb-8ab0-fe3c6beff0f4.png">

**Comment by c3founder** [comment]
The happens sometimes. You can reload the pdf viewer by pressing the pen icon on the top right of the file.
