### ISSUE TITLE
A small bug in Time Tracking

### ISSUE THREAD

**Issue by aka-phrankie** [c3founder/Roam-Enhancement#28]
Hello developers. I've encountered a bug while using it.

I am a user with Chinese as the common language.Everything is fine when timer-activated.running, but when I pause, it becomes 0s. And when I mouse click the block again, all the time accumulation is cleared. Other functions are fine.

When I click to his reference screen. I found out that it is stored in Chinese format 'AM/PM',
Maybe this is the reason for the error? Even if I change the system language to English, he still recurs.Perhaps replacing all the time variables with 24-hour binary could improve it?

![](https://gitee.com/leeda_git/frankpic/raw/master/img/bug.gif)

![](https://gitee.com/leeda_git/frankpic/raw/master/img/20210613155753.png)

**Comment by c3founder** [comment]
Hi @LIL-YAML thanks for reporting this and the insight. It should be fixed now. Please let me know.
