### ISSUE TITLE
Auto-RTL stopped working after updating to new js code

### ISSUE THREAD

**Issue by jrykner** [c3founder/Roam-Enhancement#31]
I was using the older RTL-LTR js code,
I just updated to the new code, and it doesn't work on my roam despite refreshing
var s = document.createElement("script");
s.type = "text/javascript";
s.src = "https://c3founder.github.io/Roam-Enhancement/enhancedLanguage.js";
document.getElementsByTagName("head")[0].appendChild(s);

any ideas what could cause that?
any chance that ROAM42 might be the cause?

would love to get your assistance in getting it to work

**Comment by c3founder** [comment]
Do you import the css file too? Notice that all css imports need to be before any other css code to work.

**Comment by jrykner** [comment]
yes I did, but yeah it seems that when I moved the css to be before all the others css blocks as you suggested it now seems to work fine,so thanks :)

**Comment by jrykner** [comment]
yes,I have imported the css file as well, as you suggested I moved the css block to be the first one, but still doesn't work, text doesn't AUTO RTL like it used to with the old code version (tried reloading,turning off and on the js block etc)
