### ISSUE TITLE
Issues installing PDF highlighter

### ISSUE THREAD

**Issue by wsunadawong** [c3founder/Roam-Enhancement#33]
I'm having trouble installing the PDF highlighter. I tried following the instructions, but when I upload a PDF, I'm not able to highlight anything. Here's my installation:
![image](https://user-images.githubusercontent.com/37743253/132595269-48df1554-bf44-4d03-83e0-2251af25a088.png)
![image](https://user-images.githubusercontent.com/37743253/132595372-55d62b23-74e5-4f16-a112-3ab35ac06421.png)

And here's a picture of what I see when I upload a PDF. It won't let me highlight:
![image](https://user-images.githubusercontent.com/37743253/132595437-797eb818-0cbf-4e01-a3b7-478d0acd2230.png)

Any help would be appreciated! Thanks.

**Comment by c3founder** [comment]
Hey Duck, can you check the area highlight? Hold alt and select an area with the mouse. This pdf text seems to be hard to recognize for pdf.js. The only option to extract the text would be area highlight and then use the OCR extension. 

To check the text selection, try another pdf and let me know.

**Comment by wsunadawong** [comment]
Ah my mistake, alt + select works! Thanks for the help. 😃
