### ISSUE TITLE
Button no longer link to highlight on new PDF files

### ISSUE THREAD

**Issue by viet-pham01** [c3founder/Roam-Enhancement#35]
The button at the end of the highlighted part can no longer be use to lead to the highlighted part on the pdf files. This only happen to the newly added file but not older files. As you can see. the buttons are no longer turn to the "rounded one"

![1122](https://user-images.githubusercontent.com/40406700/139671354-80734a12-29a6-4076-a4d5-ad7695e2cf85.PNG)

**Comment by c3founder** [comment]
Anything in the console? Also, can you please remove the [[[[]]]] from the end of the highlight and see what happens?

**Comment by viet-pham01** [comment]
Hi, thanks a lot for respond. I found the problem. Somehow the [[]] appear at the star of the file link around the "pdf" it is like this [[pdf]]: https://firebasestorage.googleapis.com . I removed the brackets and things work fine. I don't know what cause this because I haven't change anything the last time I used it. May be some conflict from the newly update from roam?

**Comment by hoanglong232** [comment]
I have the same problem, it start today and it affects my note as well and I don't change any setting. I try to reinstall the CSS and JS code from CCC PDF Highlit but can't fix the problem

![image](https://user-images.githubusercontent.com/85687760/140695688-07b99a73-c593-40df-b10c-81fb921b0581.png)

**Comment by viet-pham01** [comment]
> I have the same problem, it start today and it affects my old note as well. I try to reinstall the CSS and JS code but can't fix the problem
> 
> ![image](https://user-images.githubusercontent.com/85687760/140695688-07b99a73-c593-40df-b10c-81fb921b0581.png)

Hey, read the comment above. Delete the [[]] in [[pdf]] and things would be ok.

**Comment by hoanglong232** [comment]
> m, it start today and it affects my old note as well. I try to reinstall the CSS and JS code but can't fix the problem

Thanks so much, it is fixed. So I believed Roam had an update so it create that bug :D 

Since Roam Research and PDF highlight from CCC become so important to my academic workflow when some problem happens, I freak out and feel really nervous. Thank you so much @viet-pham01 for this.
