### ISSUE TITLE
PDF Enhanced not working

### ISSUE THREAD

**Issue by KoenVdB** [c3founder/Roam-Enhancement#38]
Installed PDF Enhanced on Roam today, both JS and CSS.
The highlight options working, including the references etc, but these icons on the PDF itself or within the highlights are not showing.
I use Roam on Apple devices mainly.
Import of CSS is above all other entries. 
Thoughts anyone?

**Comment by marvinscherer** [comment]
Hello, I'm having the same problem. I've used C3 highlight a lot in the past and now it is just not working anymore. My PDFs are not loading in the proper size and all the highlights on my pdfs are just gone.

Does someone else have this problem? Do you guys know how to fix it?

**Comment by sai-prasanna** [comment]
@c3founder I have the same problem. Will this library be maintained actively or is it in a frozen state? Just asking, no pressure, I know that maintaining OSS projects takes a lot of time.

**Comment by c3founder** [comment]
It should be working now
