### ISSUE TITLE
Highlight button square, only one and not working

### ISSUE THREAD

**Issue by kvistgaard** [c3founder/Roam-Enhancement#39]
I have a number of issues with the PDF Highlighter:

1. The highlight button doesn't do anything when pressed
2. The highlight button is square, not round
3. The PDF icon is missing: {{2: rhvitUT_Y}} [ ](((eGQSlT9TI)))
4. The highlight heading parameters is not respected (it should be [[Highlight]]s, not **Highlights**)

![image](https://user-images.githubusercontent.com/7572721/147870533-224ae8f2-133d-4d9a-a2b4-985efe4d4c0c.png)

I'm using Vivaldi on Windows.

Things tried:

- Removing the [[]] around pdf.

**Comment by c3founder** [comment]
Can you try another browser and let me know if it fixes it?

**Comment by kvistgaard** [comment]
Tried with Firefox. It's the same.

**Comment by c3founder** [comment]
This is fixed now. Thanks for reporting!
