### ISSUE TITLE
PDF Highlighter: Preview button not rendered

### ISSUE THREAD

**Issue by Haas-Robert** [c3founder/Roam-Enhancement#43]
Hey! 

First of all, thank you for this amazing add-on for Roam! It works great. The only thing I'm struggling with is a preview of a PDF on mouseover. The problem is that there is no page icon visible (the brackets ar empty).

<img width="465" alt="Screenshot 2022-02-12 at 14 10 47" src="https://user-images.githubusercontent.com/99485132/153712785-469bb16f-ecd9-42ec-b40c-9981b3a55f02.png">

My current setup:

<img width="1207" alt="Screenshot 2022-02-12 at 13 52 35" src="https://user-images.githubusercontent.com/99485132/153712235-6fb7428f-2698-4a7d-9ec8-e78c159fd71b.png">

I have both JS and CSS latest versions installed.

Platform: MacOS/Brave Browser (all shields down)

Thanks for any help!
Rob.

**Comment by c3founder** [comment]
Hi, from version 1.0 the pdf preview button was removed. So it works as expected. Any reason you need this?

**Comment by Haas-Robert** [comment]
Hi, Thanks for the information. I don't miss the function itself, but the link is still active in the code (although only on a few pixels), and the preview window flashes when I hover over it. That's why I was under the impression that it was a bug.
